### ISSUE TITLE
Pods install failed with Invalid `RNKeychain.podspec` file: undefined method `visionos' for #<Pod::Specification name="RNKeychain"

### ISSUE THREAD

**Issue by Maximow91** [oblador/react-native-keychain#626]
![aaaaa](https://github.com/oblador/react-native-keychain/assets/91915631/70b5f0bb-6ce6-4b11-b665-046ef6fd5220)

if i delete this line    s.visionos.deployment_target = '1.0' from node_modules/react-native-keychain/RNKeychain.podspec , pods install with success

**Comment by popurivenu** [comment]
same here

**Comment by UraFIZ** [comment]
same here

**Comment by sujathasperi2022** [comment]
With the new version 8.2.0 this is happening. Please do something about it.
It is working fine on another project with version 8.1.2.

**Comment by c100k** [comment]
Duplicates #624

**Comment by compwron** [comment]
same problem for me

**Comment by emoralesespya** [comment]
> ![aaaaa](https://private-user-images.githubusercontent.com/91915631/311681018-70b5f0bb-6ce6-4b11-b665-046ef6fd5220.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDI5NzksIm5iZiI6MTcyMzE0MjY3OSwicGF0aCI6Ii85MTkxNTYzMS8zMTE2ODEwMTgtNzBiNWYwYmItNmNlNi00YjExLWI2NjUtMDQ2ZWY2ZmQ1MjIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE4NDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzQ4NTcwMWE2ZjRjMDE4OGE2YmQ2MjI0MDY1ZTg5ZDY5NTc2MTkzNGRhZjY2NGI2ZWM3NmQ5ZTE2ZmE4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7myxFnMZWwej8FUsvJXUJUY_-0x_2DiQPKgaStcXcDs)
> 
> if i delete this line s.visionos.deployment_target = '1.0' from node_modules/react-native-keychain/RNKeychain.podspec , pods install with success

Hey guys, In my case I only update cocoapods 1.11.0 to 1.15.2

**Comment by DorianMazur** [comment]
Fixed in version 9.0.0.
