### ISSUE TITLE
does not work on react-native 0.60.4

### ISSUE THREAD

**Issue by muhammadwfa** [oblador/react-native-keychain#237]

**Comment by usrbowe** [comment]
I do face similar issue. Although issue doesn't specify details.

In my case, iOS works fine. On Android emulator/device I always get `null` from `getSupportedBiometryType()` method. Previously worked fine.

I have:
`react-native: 0.60.4`
`react-native-keychain: 3.1.3`


Code example:
```
Keychain.getSupportedBiometryType().then(biometryType => {
console.log(biometryType);
})
```

**Comment by paulrking** [comment]
After upgrading RN to 0.60.5 I cannot build Android app.  I'm getting the following error and many others like it:

.../node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/PrefsStorage.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^

I've searched the web for solution and tried many different things but have not found the solution.  Any help is greatly appreciated.

**Comment by usrbowe** [comment]
> annotation

Are you sure, you run `jetifier` before running the build command? The safest way is to run `yarn react-native run-android`.
This seems to be related to Android X.

**Comment by gastonyelmini** [comment]
> I do face similar issue. Although issue doesn't specify details.
> 
> In my case, iOS works fine. On Android emulator/device I always get `null` from `getSupportedBiometryType()` method. Previously worked fine.
> 
> I have:
> `react-native: 0.60.4`
> `react-native-keychain: 3.1.3`
> 
> Code example:
> 
> ```
> Keychain.getSupportedBiometryType().then(biometryType => {
> console.log(biometryType);
> })
> ```

Same problem than @usrbowe.

I have: 
`react-native: 0.60.5`
`react-native-keychain: 3.1.3`

**Comment by vonovak** [comment]
this should be fixed with version 4. Please open a new issue if you still encounter this.
