### ISSUE TITLE
[BUG] NoClassDefFoundError: Failed resolution of: Landroidx/datastore/preferences/PreferenceDataStoreDelegateKt

### ISSUE THREAD

**Issue by jesuscc1993** [oblador/react-native-keychain#715]
When trying to upgrade to version 9.x, I get the following error:
```
FATAL EXCEPTION: create_react_context
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/datastore/preferences/PreferenceDataStoreDelegateKt;
	at com.oblador.keychain.DataStorePrefsStorage.<init>(DataStorePrefsStorage.kt:30)
	at com.oblador.keychain.KeychainModule.<init>(KeychainModule.kt:153)
	at com.oblador.keychain.KeychainModule$Companion.withWarming(KeychainModule.kt:701)
	at com.oblador.keychain.KeychainModuleBuilder.build(KeychainModuleBuilder.kt:27)
	at com.oblador.keychain.KeychainPackage.createNativeModules(KeychainPackage.kt:13)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1467)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1438)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1340)
	at com.facebook.react.ReactInstanceManager.-$$Nest$mcreateReactContext(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.datastore.preferences.PreferenceDataStoreDelegateKt" on path: DexPathList[[zip file "/data/app/~~7Dvzu8rm9wy-quJrWi0SeQ==/com.shire.mypkfit-nLbozhFbCaMmeoTK5Niv0A==/base.apk"],nativeLibraryDirectories=[/data/app/~~7Dvzu8rm9wy-quJrWi0SeQ==/com.shire.mypkfit-nLbozhFbCaMmeoTK5Niv0A==/lib/arm64, /data/app/~~7Dvzu8rm9wy-quJrWi0SeQ==/com.shire.mypkfit-nLbozhFbCaMmeoTK5Niv0A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.oblador.keychain.DataStorePrefsStorage.<init>(DataStorePrefsStorage.kt:30) 
	at com.oblador.keychain.KeychainModule.<init>(KeychainModule.kt:153) 
	at com.oblador.keychain.KeychainModule$Companion.withWarming(KeychainModule.kt:701) 
	at com.oblador.keychain.KeychainModuleBuilder.build(KeychainModuleBuilder.kt:27) 
	at com.oblador.keychain.KeychainPackage.createNativeModules(KeychainPackage.kt:13) 
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42) 
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42) 
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1467) 
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1438) 
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1340) 
	at com.facebook.react.ReactInstanceManager.-$$Nest$mcreateReactContext(Unknown Source:0) 
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111) 
	at java.lang.Thread.run(Thread.java:920)
```
`./gradlew dependencies` does not list this dependency for me, but I have seen it in the source code, so I have tried manually adding
```
implementation "androidx.datastore:datastore-preferences:1.1.1"
```
to `android/app/build.gradle` but, even though it does then show up with `./gradlew dependencies`, the issue persists.

Relevant versions used:
* react: 18.2.0
* react-native: 0.72.3
* buildToolsVersion = "33.0.0" (tried with "34.0.0" too, with the same result)
* compileSdkVersion = 34
* minSdkVersion = 21
* targetSdkVersion = 34
* kotlinVersion = "1.8.22"
* jdk = 11

**Comment by DorianMazur** [comment]
Could you create a example repository demonstrating this issue?

**Comment by P0diceps** [comment]
I have the same issue

**Comment by RutvinCoditas** [comment]
I am also facing the same issue after updating lib from 8.2.0 latest version.

**Comment by crackhack8266** [comment]
I'm also facing the same issue 
please @oblador look into it

**Comment by bogue** [comment]
Add me to the list

**Comment by fparrav** [comment]
## ✅ Confirmed Solution for Target SDK 35

  I have successfully resolved this issue completely. The solution involves changing the DataStore initialization pattern:

  **Problem**: The `preferencesDataStore` extension function generates delegate classes that cause `NoClassDefFoundError` at runtime.

  **Solution**: Use `PreferenceDataStoreFactory.create()` directly.

  ## 📁 File Changes Required

  ### 1. `android/src/main/java/com/oblador/keychain/DataStorePrefsStorage.kt`

  **Before (problematic):**
  ```kotlin
  private val Context.prefs: DataStore<Preferences> by preferencesDataStore(
    name = KEYCHAIN_DATA,
    produceMigrations = ::sharedPreferencesMigration,
    scope = coroutineScope,
  )
   private val prefs: DataStore<Preferences> = reactContext.prefs
```
  **After (working):**
  ```kotlin
  private val prefs: DataStore<Preferences> = PreferenceDataStoreFactory.create(
    corruptionHandler = null,
    migrations = sharedPreferencesMigration(reactContext),
    scope = coroutineScope
  ) {
    reactContext.preferencesDataStoreFile(KEYCHAIN_DATA)
  }
  ```
  Additional imports to add:
  ```kotlin
  import androidx.datastore.preferences.core.PreferenceDataStoreFactory
  import androidx.datastore.preferences.preferencesDataStoreFile
  ```


  ✅ Result

  App works with target SDK 35 + React Native + DataStore without crashes.

  Tested on:
  - React Native 0.72+
  - Target SDK 35
  - react-native-keychain v10.0.0

  This solution maintains all DataStore functionality including SharedPreferences migration while avoiding the delegate pattern that causes runtime class
  resolution issues.
