### ISSUE TITLE
Compilation fails with release 3.1.0 (Oreo)

### ISSUE THREAD

**Issue by blelem** [oblador/react-native-keychain#196]
When upgrading from 3.0.0 to 3.1.0, compilation fails with
```
 :react-native-keychain:compileDebugJavaWithJavac...\node_modules\react-native-keychain\android\src\main\java\com\oblador\keychain\cipherStorage\CipherStorageKeystoreAESCBC.java:28: error: cannot find symbol
import android.security.keystore.StrongBoxUnavailableException;
                                ^
  symbol:   class StrongBoxUnavailableException
  location: package android.security.keystore
```
Turns out that the Android SDK installed on my PC was still at **8.1 (Oreo) - API 27**, and for the 3.1.0 library, **9.0 (Pie) - API 28** is required. Upgrading my SDK to pie solved the issue. 

--
No actions expected from this "issue", I just wanted to document it so the next souls to whom this happens will know what to do.
